name: Helium
options:
  bundleIdPrefix: dev.helium
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  Helium:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Helium
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.helium
        INFOPLIST_FILE: Helium/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - framework: HeliumRust.xcframework
      - sdk: UIKit.framework
      - sdk: Metal.framework
      - sdk: QuartzCore.framework

